name: release

on:
 push:
  tags:
    - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    env:
      BLACKSMITH_FORGE_USERNAME: puppetlabs
      BLACKSMITH_FORGE_PASSWORD: {{ env.FORGE_API_KEY }}
    runs-on: ubuntu-latest
    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.3
    - name: Update Rubygems
      run: gem update --system 3.1.0
    - name: Get latest tag
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        ref: ${{ env.RELEASE_VERSION }}
    - name: Bundle install
      run: bundle install --with release
    - name: Build module
      run: bundle exec rake module:build
    - name: Publish module
      run: bundle exec rake module:push

